version: '2'


networks:
  default:
    external:
      name: fab-net

services:
   ca.fabric.com:
      container_name: ca.fabric.com
      image: hyperledger/fabric-ca:amd64-1.4.2-snapshot-4289522
      command: sh -c 'fabric-ca-server start -d -b rca-orderer-admin:rca-orderer-adminpw --port 7152 --cfg.identities.allowremove'
      environment:
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CA_NAME=ca.fabric.com
         - FABRIC_CA_SERVER_CSR_CN=ca.fabric.com
         - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
         - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca/ca/ca.fabric.com-key.pem
         - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca/ca/ca.fabric.com-cert.pem
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ../fabca/fabric.com/ca-server:/etc/hyperledger/fabric-ca
         - ../crypto-config/ordererOrganizations/fabric.com/ca:/etc/hyperledger/fabric-ca/ca
         - ../scripts:/scripts
      ports:
         - 7152:7152
         
   ca.po1.fabric.com:
      container_name: ca.po1.fabric.com
      image: hyperledger/fabric-ca:amd64-1.4.2-snapshot-4289522
      command: sh -c 'fabric-ca-server start -d -b rca-po1-admin:rca-po1-adminpw --port 7153 --cfg.identities.allowremove'
      environment:
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CA_NAME=ca.po1.fabric.com
         - FABRIC_CA_SERVER_CSR_CN=ca.po1.fabric.com
         - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
         - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca/ca/ca.po1.fabric.com-key.pem
         - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca/ca/ca.po1.fabric.com-cert.pem
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ../fabca/po1.fabric.com/ca-server:/etc/hyperledger/fabric-ca
         - ../crypto-config/peerOrganizations/po1.fabric.com/ca:/etc/hyperledger/fabric-ca/ca
         - ../scripts:/scripts
      ports:
         - 7153:7153